export const labels = [
  'book',
  'copy',
  'task-dependency-pre',
  'triangle-up',
  'verified',
  'panel',
  'code',
  'filter',
  'chevron-up-o',
  'chevron-left-o-fill',
  'lock',
  'approve',
  'bell-fill',
  'descending',
  'overview',
  'play-o',
  'chevron-down-o-fill',
  'branch',
  'arrow-down-o-fill',
  'triangle-left',
  'single-chat-bubble',
  'arrow-up-o',
  'reorder',
  'chevrons-expand-horizontal',
  'custom-text',
  'undo',
  'download-file',
  'solidDown',
  'calendar-tick',
  'more-o-fill',
  'stage',
  'chat-group-stroke',
  'checkbox-checked-fill',
  'arrows-pinch',
  'add',
  'knowledge-base',
  'chat-private-stroke',
  'h1',
  'drag',
  'office-powerpoint',
  'col-before',
  'team-medal',
  'arrow-clock-right',
  'target',
  'client',
  'facebook',
  'priorityflag',
  'log-out',
  'switch1',
  'xiaomi',
  'task-dependency-post',
  'home',
  'building',
  'figma',
  'plus-o',
  'arrow-roundleft',
  'org-crown',
  'import',
  'italic',
  'arrows-cycle',
  'arrow-out',
  'plus-box-fill',
  'plus-o-fill',
  'arrows-full-expand',
  'markdown',
  'chevron-right',
  'google',
  'row-before',
  'share-stage',
  'add-test',
  'user-question',
  'attachment',
  'cry',
  'warning-o',
  'alert-clock',
  'toggle-left',
  'region-fill',
  'arrows-pinch-out',
  'question-o-fill',
  'loading',
  'dingding',
  'chevron-up-o-fill',
  'clear',
  'import-project',
  'multi-number',
  'arrow-down-o',
  'rich-text',
  'set',
  'progress',
  'info',
  'dashboard',
  'team-graph',
  'top-up-fill',
  'shortcut',
  'pause-o',
  'region',
  'file',
  'queding',
  'user-disable',
  'to-do',
  'robot',
  'scan',
  'crop',
  'dribbble',
  'more',
  'heading',
  'triangle-right-o',
  'building-fill',
  'chevron-up',
  'task-tick',
  'cuvette',
  'milestone',
  'col-after',
  'checkbox-checked',
  'org-book',
  'link',
  'team-talk',
  'Aone',
  'discussion-fill',
  'intro',
  'underline',
  'redo',
  'moon',
  'ip-box-fill',
  'created-fill',
  'edit',
  'grid',
  'tree',
  'wechat',
  'sun',
  'qq',
  'focus',
  'video',
  'palette',
  'zhihu',
  'task-board',
  'expand-oblique',
  'bulb',
  'ip',
  'safety',
  'bookkeeping-logo',
  'blockquote',
  'triangle-down',
  'arrow-hollow-down',
  'compass-o',
  'sort',
  'warning-o-fill',
  'rss',
  'home-fill',
  'github',
  'box-plus',
  'processon',
  'wps',
  'oldman',
  'menu',
  'user-add',
  'team-location',
  'report-overview',
  'double-tick',
  'team-building',
  'chevron-right-o',
  'intelligent-assistant',
  'team-pen',
  'favorite-fill',
  'org-projects',
  'weibo',
  'chevrons-left',
  'meta',
  'starstroke',
  'tex',
  'arrow-right1',
  'column',
  'douban',
  'folder',
  'remove',
  'custom-field',
  'risk',
  'question-talk',
  'align-left',
  'arrow-roundright',
  'add-folder',
  'align-right',
  'add-user-set',
  'triangle-right',
  'multiplechoice',
  'team-loudspeaker',
  'team-terminal',
  'contact',
  'collection',
  'arrow-left-o',
  'post',
  'upload-pic',
  'detail',
  'clock',
  'tag-fill',
  'users-fill',
  'upload',
  'pencil-fill',
  'picture',
  'arrow-up-o-fill',
  'teambition',
  'question-o',
  'list',
  'tick-o',
  'search',
  'arrow-down1',
  'tongzhi',
  'eye-close',
  'like-fill',
  'line-through',
  'share1',
  'twitter',
  'chevron-right-o-fill',
  'evernote',
  'histogram',
  'size-grid',
  'tick-bold',
  'org-apps',
  'timeline',
  'zendesk',
  'arrow-clock-left',
  'info-o-fill',
  'custom-number',
  'fangcloud',
  'computer',
  'tick-o-fill',
  'jinshuju',
  'align-center',
  'disable',
  'user-switch',
  'chevrons-collapse-vertical',
  'chevron-down-o',
  'minus',
  'permission',
  'arrows-full-collapse',
  'h2',
  'arrow-right-o-fill',
  'user-fill',
  'team-tie',
  'user-externa',
  'team-calculator',
  'unlock',
  'team-bulb',
  'demo',
  'chevron-down',
  'chevrons-expand-vertical',
  'remove-o',
  'arrow-up1',
  'table',
  'checkbox',
  'print',
  'enterprise-calendar',
  'star-fill',
  'invistion',
  'smile',
  'arrow-in',
  'normal',
  'arrow-left-o-fill',
  'stack-tick',
  'arrow-upright-o-fill',
  'collapse',
  'email',
  'sprint',
  'screenshot',
  'exit',
  'team-stamp',
  'download',
  'teambition-outline',
  'pinterest',
  'user-search',
  'arrow-right-o',
  'remove-o-fill',
  'bold',
  'calendar',
  'sorting',
  'stack-tick-fill',
  'team-briefcase',
  'team-bus',
  'chevron-left-o',
  'headset',
  'double-box-plus',
  'distribute',
  'unlink',
  'share-stroke',
  'pencil',
  'team-flag',
  'netease',
  'export',
  'degree',
  'arrow-left1',
  'aliyun',
  'pin-fill',
  'like',
  'h3',
  'dock',
  'comments',
  'expand',
  'created',
  'framer',
  'office-excel',
  'treenode-single',
  'favorite',
  'paper',
  'zoom-in',
  'user',
  'workhour',
  'mobile',
  'ashbin',
  'zoom-out',
  'save',
  'multi-selection',
  'salesman',
  'chevron-left',
  'circle',
  'briefcase-stroke',
  'unordered-list',
  'quote',
  'lightning',
  'cut',
  'wechat-enterprise',
  'team-camera',
  'ascending',
  'switch',
  'info-o',
  'clock-fill',
  'chevrons-right',
  'inbox',
  'linkedin',
  'org-medal',
  'yunzhijia',
  'more-o',
  'users',
  'ziyuan',
  'qrcode',
  'arrow-upline-o-fill',
  'dingding-o-fill',
  'toggle-right',
  'tag',
  'row-after',
  'invite-fill',
  'task-dependency',
  'download-stage',
  'play-outline',
  'paragraph',
  'compass-fill',
  'dropbox',
  'inbox1',
  'eye',
  'unfold',
  'tick',
  'pin',
  'newtab',
  'arrow-hollow-up',
  'single-selection',
  'user-o',
  'office-word',
  'earth',
  'chat-private',
  'minus-o',
  'gitlab',
];

export const labelMap = {
  smile: '',
  cry: '',
  success: '',
  warning: '',
  prompt: '',
  error: '',
  help: '',
  clock: '',
  'success-filling': '',
  'delete-filling': '',
  'favorites-filling': '',
  add: '',
  minus: '',
  'arrow-up': '',
  'arrow-down': '',
  'arrow-left': '',
  'arrow-right': '',
  'arrow-double-left': '',
  'arrow-double-right': '',
  switch: '',
  sorting: '',
  descending: '',
  ascending: '',
  select: '',
  'semi-select': '',
  loading: '',
  search: '',
  close: '',
  ellipsis: '',
  picture: '',
  calendar: '',
  ashbin: '',
  upload: '',
  download: '',
  set: '',
  edit: '',
  refresh: '',
  filter: '',
  attachment: '',
  account: '',
  email: '',
  atm: '',
  copy: '',
  'toggle-left': '',
  'toggle-right': '',
  eye: '',
  'eye-close': '',
  unlock: '',
  lock: '',
  exit: '',
  'chart-bar': '',
  'chart-pie': '',
  form: '',
  detail: '',
  list: '',
  dashboard: '',
  yincang: '',
  huabanfuben56: '',
  settings: '',
  'triangle-down': '',
  'triangle-right': '',
  'triangle-up': '',
  trash: '',
  star: '',
  sort: '',
  seeMoreRepositories: '',
  pass: '',
  output: '',
  repositories: '',
  notice: '',
  member: '',
  'mr-path': '',
  more: '',
  mergeRequest: '',
  info: '',
  issue: '',
  cancel: '',
  delete: '',
  check: '',
  group: '',
  'back-arrow': '',
  'add-user': '',
  addGroup: '',
  'add-nav': '',
  'state-check': '',
  warning1: '',
  'circle-remove': '',
  'circle-info': '',
  'circle-plus': '',
  queding: '',
  ziyuan: '',
  solidDown: '',
  'triangle-right-s': '',
  'triangle-down-s': '',
  'triangle-left-s': '',
  'triangle-up-s': '',
  'plus-o-fill': '',
  'dingding-o-fill': '',
  'emoji-frown': '',
  histogram: '',
  jinshuju: '',
  overview: '',
  markdown: '',
  workhour: '',
  pinterest: '',
  'discussion-fill': '',
  'office-excel': '',
  'invite-fill': '',
  paragraph: '',
  priorityflag: '',
  'line-through': '',
  'office-powerpoint': '',
  'pause-o': '',
  h2: '',
  plus: '',
  'info-o': '',
  'question-o-fill': '',
  processon: '',
  'remove-o-fill': '',
  quote: '',
  'remove-o': '',
  'row-before': '',
  remove: '',
  robot: '',
  screenshot: '',
  'row-after': '',
  rss: '',
  sprint: '',
  'tick-bold': '',
  salesman: '',
  'tick-o': '',
  scan: '',
  timeline: '',
  tick: '',
  'task-tick': '',
  'teambition-outline': '',
  switch1: '',
  tex: '',
  'user-add': '',
  'tick-o-fill': '',
  'user-fill': '',
  'timeline-s': '',
  twitter: '',
  'user-search': '',
  teambition: '',
  'triangle-right-o': '',
  'warning-o': '',
  'user-switch': '',
  underline: '',
  xiaomi: '',
  'users-fill': '',
  'users-s': '',
  'user-disable': '',
  'user-externa': '',
  netease: '',
  'user-o': '',
  'user-question': '',
  grid: '',
  wechat: '',
  'warning-o-fill': '',
  users: '',
  yunzhijia: '',
  'wechat-enterprise': '',
  user: '',
  zhihu: '',
  zendesk: '',
  weibo: '',
  qq: '',
  oldman: '',
  wps: '',
  'question-o': '',
  'arrows-long-down': '',
  'arrows-long-up': '',
  clock1: '',
  calendar1: '',
  email1: '',
  loading1: '',
  eye1: '',
  filter1: '',
  paperclip: '',
  picture1: '',
  trashbin: '',
  'eye-slash': '',
  'star-fill': '',
  gear: '',
  search1: '',
  'paper-pen': '',
  selection: '',
  lightning: '',
  starstroke: '',
  post: '',
  book: '',
  intro: '',
  share1: '',
  'quetion-o': '',
  'play-o': '',
  pencil: '',
  'alert-clock': '',
  branch: '',
  menu: '',
  copy1: '',
  save: '',
  link: '',
  'region-fill': '',
  region: '',
  ip: '',
  'ip-box-fill': '',
  building: '',
  'team-briefcase': '',
  'team-bus': '',
  'team-calculator': '',
  'team-bulb': '',
  'team-location': '',
  'team-compass': '',
  'team-flag': '',
  'team-graph': '',
  'team-camera': '',
  'team-loudspeaker': '',
  'team-medal': '',
  'team-notebook': '',
  'team-talk': '',
  'team-stamp': '',
  'team-terminal': '',
  'team-tie': '',
  'team-pen': '',
  tree: '',
  clear: '',
  'normal-text': '',
  reorder: '',
  permission: '',
  'chat-group-stroke': '',
  'briefcase-stroke': '',
  'org-apps': '',
  'org-book': '',
  'team-building': '',
  'triangle-left': '',
  'org-medal': '',
  'org-crown': '',
  'add-user-set': '',
  qrcode: '',
  bulb: '',
  inbox: '',
  'rich-text': '',
  export: '',
  upload1: '',
  download1: '',
  import: '',
  cut: '',
  'share-stroke': '',
  unlink: '',
  'zoom-out': '',
  'zoom-in': '',
  table: '',
  earth: '',
  'align-right': '',
  'clock-fill': '',
  aliyun: '',
  'home-fill': '',
  'align-center': '',
  home: '',
  'arrow-clock-left': '',
  'favorite-fill': '',
  'arrow-down-o': '',
  favorite: '',
  apps: '',
  'pencil-fill': '',
  'arrow-left1': '',
  palette: '',
  'arrow-left-o-fill': '',
  collection: '',
  'arrow-hollow-up': '',
  pin: '',
  'arrow-clock-right': '',
  mobile: '',
  'arrow-hollow-down': '',
  computer: '',
  'arrow-down1': '',
  unlock1: '',
  'arrow-down-o-fill': '',
  lock1: '',
  'arrow-right1': '',
  headset: '',
  'arrow-right-o': '',
  'unordered-list': '',
  'arrow-left-o': '',
  undo: '',
  'arrow-right-o-fill': '',
  redo: '',
  'arrow-up1': '',
  code: '',
  'arrow-up-o-fill': '',
  file: '',
  'arrow-roundleft': '',
  'custom-text': '',
  'arrow-roundright': '',
  'multi-selection': '',
  'arrow-up-o': '',
  'custom-number': '',
  'arrow-upline-o-fill': '',
  'single-selection': '',
  'arrow-upright-o-fill': '',
  panel: '',
  'align-left': '',
  meta: '',
  'arrows-full-collapse': '',
  safety: '',
  'arrows-pinch': '',
  'add-folder': '',
  'arrows-cycle': '',
  'add-test': '',
  'arrows-pinch-out': '',
  approve: '',
  'arrows-swtich-vertical': '',
  Aone: '',
  blockquote: '',
  cuvette: '',
  'checkbox-checked-fill': '',
  demo: '',
  'arrows-full-expand': '',
  dock: '',
  'box-plus': '',
  'download-file': '',
  'chevron-down': '',
  'share-stage': '',
  'chevron-down-o-fill': '',
  stage: '',
  'chevron-down-o': '',
  'download-stage': '',
  checkbox: '',
  'upload-pic': '',
  'chevron-left-s': '',
  'top-up-fill': '',
  'chevron-left-o': '',
  folder: '',
  'chevron-right-o-fill': '',
  moon: '',
  bold: '',
  sun: '',
  'arrows-swtich-horizontal': '',
  'knowledge-base': '',
  'chevron-right': '',
  'question-talk': '',
  'chevron-right-o': '',
  paper: '',
  'chevron-left': '',
  'bell-fill': '',
  'chevron-down-s': '',
  'stack-tick': '',
  'chevrons-collapse-vertical': '',
  tachometer: '',
  'chevron-up-s': '',
  focus: '',
  'chevron-up': '',
  tag: '',
  'chevrons-expand-vertical': '',
  'stack-tick-fill': '',
  'chevrons-expand-horizontal': '',
  normal: '',
  'chevron-right-s': '',
  'multi-number': '',
  'chevrons-right': '',
  'play-outline': '',
  'col-after': '',
  'org-projects': '',
  'chevrons-left': '',
  wall: '',
  'chevron-up-o': '',
  newtab: '',
  column: '',
  'bookkeeping-logo': '',
  contact: '',
  risk: '',
  crop: '',
  verified: '',
  douban: '',
  target: '',
  degree: '',
  preview: '',
  'checkbox-checked': '',
  'enterprise-calendar': '',
  client: '',
  'arrow-in': '',
  'chevron-left-o-fill': '',
  'arrow-out': '',
  drag: '',
  'task-dependency': '',
  'col-before': '',
  'task-dependency-pre': '',
  expand: '',
  'task-dependency-post': '',
  'double-tick': '',
  milestone: '',
  dingding: '',
  'custom-field': '',
  'double-box-plus': '',
  print: '',
  figma: '',
  'single-chat-bubble': '',
  evernote: '',
  like: '',
  'chevron-up-o-fill': '',
  distribute: '',
  circle: '',
  'like-fill': '',
  dribbble: '',
  progress: '',
  fangcloud: '',
  'pin-fill': '',
  framer: '',
  'chat-private': '',
  facebook: '',
  ding: '',
  'emoji-smile': '',
  unfold: '',
  heading: '',
  'intelligent-assistant': '',
  'info-o-fill': '',
  'expand-oblique': '',
  horizontal: '',
  'report-overview': '',
  h1: '',
  'calendar-tick': '',
  collapse: '',
  created: '',
  'task-board': '',
  'more-o-fill': '',
  shortcut: '',
  google: '',
  'log-out': '',
  disable: '',
  'import-project': '',
  h3: '',
  video: '',
  italic: '',
  'size-grid': '',
  invistion: '',
  multiplechoice: '',
  github: '',
  inbox1: '',
  dropbox: '',
  comments: '',
  'tag-fill': '',
  linkedin: '',
  'building-fill': '',
  'more-o': '',
  'created-fill': '',
  'minus-o': '',
  'plus-mobile': '',
  'plus-o': '',
  'chat-private-stroke': '',
  'plus-box-fill': '',
  'to-do': '',
  'office-word': '',
  'treenode-single': '',
  'zhizhen-compass-line': '',
  'zhizhen-compass-fill': '',
  gitlab: '',
  'compass-o': '',
  'compass-fill': '',
  tongzhi: '',
};
